dist: trusty
language: go
compiler: go
before_script:
script: make test -j4
addons:
  apt:
    packages:
      - libglu1-mesa-dev
      - libgles2-mesa-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libasound2-dev
